---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-deploy
  namespace: wego-system
spec:
  imageRepositoryRef:
    name: podinfo-deploy
  policy:
    semver:
      range: 6.0.x
