---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sandboxx.ap-southeast-1.eksctl.io-user
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/sandboxx.ap-southeast-1.eksctl.io/user
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-auto-github-gitops-config

